[package]
name = "raknet-python"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
rust-raknet = "0.8.0"
tokio = "1"
pyo3 = { version = "0.16.4", features = ["extension-module"] }
lazy_static = "1"